// Description     : Test typedefs of structs
// Comments        : Shorthand struct is outside a module
//****************************************************************************

typedef struct SA
{
    unsigned short USA;
    string SSA;
} mySA;

module MA
{
    interface IA
    {
        SA MethodMAIA(in long LA, out mySA objSA);
    };
};
