// Description     : Test typedefs of structs
// Comments        : Struct is declared inside a module
//****************************************************************************

module MA
{
    struct SA
    {
        unsigned short USA;
        string SSA;
    };
    typedef SA mySA;

    interface IA
    {
        SA MethodMAIA(in long LA, out mySA objSA);
    };
};
