

module LoganBerry{

  module BlackCherry{
    typedef octet Starfruit;

  };


  module Parsnip{
    typedef char Ginger;


    module Celery{
      struct Lychees{
        Parsnip::Ginger Apricots;
      };

      struct WhiteCabbage{
        ::LoganBerry::Parsnip::Ginger Apricots;
      };

    };

  };

  interface Apple{

    typedef long Orange;

    exception Mint{
      long GardenPeas;
    };
  };

  interface Banana : Apple{

    typedef Orange GaliaMelon;

    void  Sultana();
  };

};

interface Carrots : LoganBerry::Apple{

  typedef float Turnip;
};

interface idlServer : LoganBerry::Banana, Carrots{

  typedef char Orange;

  attribute ::LoganBerry::Parsnip::Celery::WhiteCabbage Aniseed;

  void  Bayleaf(
    in    ::idlServer::GaliaMelon p1,
    out   long Aniseed
  );
};

