const unsigned long hex16 = 0x10;
const unsigned long oct8 = 010;
const unsigned long dec10 = 10;

const short l = 4;

enum N { zero, un , deux, trois };

exception E {
    short cause ;
};

exception F {
    long type ;
};

module M {
    const short l = 4;

    enum N { zero, un , deux, trois };

    exception E {
        short cause ;
        };

    interface A {
            const short l = 4;

            enum N { zero, un , deux, trois };

        exception E {
            short cause ;
            };
        N foo(in N x, out N y, inout N z) raises (E, F) ;
    };
};

