/**
 * pragma - prefix, ID and version
 */
module M {

typedef long LONG_type;

#pragma prefix "omg.org"

interface A {
  void bar();
  void bar1();
  #pragma prefix "test"
  void bar2();
  void bar3();
  #pragma ID bar3 "LOCAL:weird"
};

#include "include1.idl"

module M2 {
#include "include2.idl"
};

struct S {
  char c;
};

exception E {
  long err;
};

};

#pragma version ::M::A::bar2 3.1
#pragma version M::E 2.1

#pragma prefix ""

typedef long LONG_type;

